dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - devel
  - deploy
script:
- touch foo
deploy:
  provider: pypi
  user: aleg
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true
  password:
    secure:  c+3VkRY3Mui9/EsQ2IXQiUdhiXkjKaVaEQwjOV8Ehe0JVRDxXhuXdjAhwWnbasy9zYn/QtFlJkwj5WPauHDocUONkwFaZ/KSomFDEBJ86uJGSaMMAPbzUxv5IPZlGoSDyFxA6vhCP7ZJEHFwk6y/5djr09lvVakG4LUuJS3wCWgsg0TXWG8XrbXcuvBKDk82Xv8lZUcyzXKmcpP3/ORIePSI3g85odl/0EJoO6dvvDp26WzHlTYo15N9aPN7AUIuCJ/K7H8IEKgucdedl+Op0EvfHoPjy86o0D+PHjApWNX4wTvXnjwQOitbBFjU3BEJacA3X8qCH7jPNAu+/0qayTos1z+0j9dBlNm3VVRCUEcXpxi8E6wYagBfb+Ex6cMX7aPpm0x7f+Ais5YX00XWJXNh48xkYFTmrdojfQ5w48TCThdNKyhyZjuyaXB1AajxFucUl71M8WMVGzklpp5aefYbyMcga2IAiZi9DwMfnQ/h6wNnghdseo9kvX7yXL0CEf4BmSg4lsW9JUBIujdYbtB8KGw01iY0yPfMNx/+2r5WL5AaQc+cMg0fq+SfTFMZa7gi7LLIGKpzNcCcsbWpeUniN+WDgsaOhDMUwsKhWzGVFKyuF4eOL4pOlo674ThrUvT+ZdpHF3afCn4dF7/3Si/fSdfJPvpSt4qnRlfCJeo=
