dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - devel
  - deploy
script: true
deploy:
  provider: pypi
  user: aleg
  on:
    all_branches: true
  password:
    secure: T+Obzarld83A3FmdamMZ0oAlPocogN/7sVYQpgUykxa3UUS7OT11FvixTE0bRaUNpEQyyyAsBGL38WbOkeFEQbaQCKshRomXw4/5jDtwsJgv69AfXCSIzM7P8LihPrjE0ejsizz+H3FcBaaPMZ9dkcEe/t3KML+eLbZVzNKe/U1Faek6Y2eUeFdWq+o3S9PJl8QpJwdvZdG5gLQP1WqyFr9uiSnjw/I2oxo1p8Fk06BSuymIVpea4lodkm7wKc2Ax97obpeiT6Sh0ci8A2L0PF1cMQJP7d0MyMKulVsVAXcoAEyXvdBkm9mMXoGR4binZ2Y39l7snNI8p4tgyZyJmkPOSvQcx6ULZNIbaKXY8X67oxnMbIzWKnOe3yZrnjJR9gI32/cfIb0kWBZ0dxMjFjPxXZurxo7BQ/78KupEWCUS0rBCvy5ks7wsw/erXmFGs+EVuSC3KjSI1JByubEZ+CueqfZwHihw5xHy4tuq0E3YEOAQaH9ACcJbSG0c73QrhhWNXcwFEzoLyum0rpzY6wPA1UIs1l2zhnSIszzqCu50tLL/MT4aw4Ze58XntnJwxVe2mlf+s9FoO/dVinwz6Z1R/m9dOLwHJOQv+vv2kutMiAGuKPQBy/fh5GCyGvl5laCcBXjlgjh2e/ikBl5oVd1TaL7DAi+QP4L31QEosb0=
