dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - devel
  - deploy
script: true
deploy:
  provider: pypi
  user: aleg
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true
  password: $PYPI_PW
